# Generated by Django 4.2.4 on 2023-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OT', 'Others'), ('BW', 'Baby Clothes'), ('SH', 'Shoe'), ('CL', 'Clothes'), ('BG', 'Bags')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('RX', 'Rolex'), ('VS', 'Versace'), ('GV', 'Givenchy'), ('AD', 'Addidas'), ('GC', 'Gucci'), ('LC', 'Lacosta'), ('DG', 'Dolce and Gabanna'), ('FL', 'Fila'), ('SP', 'Supreme'), ('HR', 'Hermes'), ('CK', 'Calvin Klein'), ('LV', 'Louis Vuitton')], max_length=2),
        ),
    ]
