# Generated by Django 4.2.4 on 2023-09-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category_alter_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OT', 'Others'), ('SH', 'Shoe'), ('CL', 'Clothes'), ('BW', 'Baby Clothes'), ('BG', 'Bags')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('SP', 'Supreme'), ('RX', 'Rolex'), ('CK', 'Calvin Klein'), ('LV', 'Louis Vuitton'), ('AD', 'Addidas'), ('GC', 'Gucci'), ('VS', 'Versace'), ('DG', 'Dolce and Gabanna'), ('LC', 'Lacosta'), ('FL', 'Fila'), ('HR', 'Hermes'), ('GV', 'Givenchy')], max_length=2),
        ),
    ]
