# Generated by Django 4.2.4 on 2023-09-05 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_alter_product_category_alter_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BG', 'Bags'), ('BW', 'Baby Clothes'), ('OT', 'Others'), ('SH', 'Shoe'), ('CL', 'Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('GV', 'Givenchy'), ('FL', 'Fila'), ('LC', 'Lacosta'), ('LV', 'Louis Vuitton'), ('RX', 'Rolex'), ('SP', 'Supreme'), ('GC', 'Gucci'), ('VS', 'Versace'), ('AD', 'Addidas'), ('DG', 'Dolce and Gabanna'), ('HR', 'Hermes'), ('CK', 'Calvin Klein')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
