# Generated by Django 4.2.4 on 2023-09-07 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category_alter_product_producer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('OT', 'Others'), ('CL', 'Clothes'), ('BW', 'Baby Clothes'), ('SH', 'Shoe'), ('BG', 'Bags')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('LC', 'Lacosta'), ('AD', 'Addidas'), ('LV', 'Louis Vuitton'), ('FL', 'Fila'), ('SP', 'Supreme'), ('VS', 'Versace'), ('GC', 'Gucci'), ('CK', 'Calvin Klein'), ('GV', 'Givenchy'), ('HR', 'Hermes'), ('RX', 'Rolex'), ('DG', 'Dolce and Gabanna')], max_length=2),
        ),
    ]
