# Generated by Django 3.2.21 on 2023-09-11 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_product_category_alter_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothes'), ('BG', 'Bags'), ('SH', 'Shoe'), ('BW', 'Baby Clothes'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('VS', 'Versace'), ('LV', 'Louis Vuitton'), ('RX', 'Rolex'), ('HR', 'Hermes'), ('SP', 'Supreme'), ('GV', 'Givenchy'), ('AD', 'Addidas'), ('FL', 'Fila'), ('CK', 'Calvin Klein'), ('LC', 'Lacosta'), ('DG', 'Dolce and Gabanna'), ('GC', 'Gucci')], max_length=2),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
