# Generated by Django 3.2.21 on 2023-09-12 00:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20230911_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('ON', 'Ondo'), ('NG', 'Niger'), ('DL', 'Delta'), ('AN', 'Anambra'), ('OG', 'Ogun'), ('LG', 'Lagos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='Status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('On the Way', 'On the Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothes'), ('OT', 'Others'), ('BG', 'Bags'), ('SH', 'Shoe'), ('BW', 'Baby Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('CK', 'Calvin Klein'), ('SP', 'Supreme'), ('FL', 'Fila'), ('LC', 'Lacosta'), ('LV', 'Louis Vuitton'), ('AD', 'Addidas'), ('GV', 'Givenchy'), ('RX', 'Rolex'), ('DG', 'Dolce and Gabanna'), ('VS', 'Versace'), ('GC', 'Gucci'), ('HR', 'Hermes')], max_length=2),
        ),
        migrations.CreateModel(
            name='Incart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
