# Generated by Django 3.2.21 on 2023-09-13 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20230911_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Ordered_date',
            new_name='ordered_date',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='Status',
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On the Way', 'On the Way'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('OG', 'Ogun'), ('NG', 'Niger'), ('LG', 'Lagos'), ('AN', 'Anambra'), ('ON', 'Ondo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothes'), ('BW', 'Baby Clothes'), ('OT', 'Others'), ('SH', 'Shoe'), ('BG', 'Bags')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('DG', 'Dolce and Gabanna'), ('AD', 'Addidas'), ('FL', 'Fila'), ('VS', 'Versace'), ('GV', 'Givenchy'), ('RX', 'Rolex'), ('LC', 'Lacosta'), ('LV', 'Louis Vuitton'), ('GC', 'Gucci'), ('SP', 'Supreme'), ('CK', 'Calvin Klein'), ('HR', 'Hermes')], max_length=2),
        ),
    ]
