# Generated by Django 3.2.21 on 2023-09-18 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20230914_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('LG', 'Lagos'), ('AN', 'Anambra'), ('OG', 'Ogun'), ('NG', 'Niger'), ('ON', 'Ondo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('On the Way', 'On the Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Shoe'), ('BW', 'Baby Clothes'), ('OT', 'Others'), ('BG', 'Bags'), ('CL', 'Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('VS', 'Versace'), ('LV', 'Louis Vuitton'), ('FL', 'Fila'), ('RX', 'Rolex'), ('GC', 'Gucci'), ('DG', 'Dolce and Gabanna'), ('HR', 'Hermes'), ('SP', 'Supreme'), ('CK', 'Calvin Klein'), ('AD', 'Addidas'), ('GV', 'Givenchy'), ('LC', 'Lacosta')], max_length=2),
        ),
        migrations.CreateModel(
            name='Payapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=50)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('DL', 'Delta'), ('LG', 'Lagos'), ('AN', 'Anambra'), ('OG', 'Ogun'), ('NG', 'Niger'), ('ON', 'Ondo')], max_length=20)),
                ('receipt', models.ImageField(upload_to='payment')),
                ('amount', models.FloatField()),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
