# Generated by Django 3.2.21 on 2023-09-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230918_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payapp',
            old_name='receiver',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('ON', 'Ondo'), ('OG', 'Ogun'), ('NG', 'Niger'), ('DL', 'Delta'), ('AN', 'Anambra'), ('LG', 'Lagos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('On the Way', 'On the Way'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='contact',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='receipt',
            field=models.ImageField(null=True, upload_to='payment'),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='state',
            field=models.CharField(choices=[('ON', 'Ondo'), ('OG', 'Ogun'), ('NG', 'Niger'), ('DL', 'Delta'), ('AN', 'Anambra'), ('LG', 'Lagos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BG', 'Bags'), ('SH', 'Shoe'), ('CL', 'Clothes'), ('OT', 'Others'), ('BW', 'Baby Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('CK', 'Calvin Klein'), ('FL', 'Fila'), ('GV', 'Givenchy'), ('LV', 'Louis Vuitton'), ('RX', 'Rolex'), ('VS', 'Versace'), ('SP', 'Supreme'), ('DG', 'Dolce and Gabanna'), ('HR', 'Hermes'), ('GC', 'Gucci'), ('LC', 'Lacosta'), ('AD', 'Addidas')], max_length=2),
        ),
    ]
