# Generated by Django 3.2.21 on 2023-09-18 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_auto_20230918_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('NG', 'Niger'), ('OG', 'Ogun'), ('AN', 'Anambra'), ('LG', 'Lagos'), ('ON', 'Ondo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Pending', 'Pending'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('On the Way', 'On the Way'), ('Accepted', 'Accepted')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('NG', 'Niger'), ('OG', 'Ogun'), ('AN', 'Anambra'), ('LG', 'Lagos'), ('ON', 'Ondo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Shoe'), ('BG', 'Bags'), ('CL', 'Clothes'), ('BW', 'Baby Clothes'), ('OT', 'Others')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('LC', 'Lacosta'), ('CK', 'Calvin Klein'), ('FL', 'Fila'), ('SP', 'Supreme'), ('GV', 'Givenchy'), ('AD', 'Addidas'), ('GC', 'Gucci'), ('HR', 'Hermes'), ('DG', 'Dolce and Gabanna'), ('RX', 'Rolex'), ('VS', 'Versace'), ('LV', 'Louis Vuitton')], max_length=2),
        ),
    ]
