# Generated by Django 3.2.21 on 2023-09-18 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20230918_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
        migrations.AddField(
            model_name='payapp',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('NG', 'Niger'), ('AN', 'Anambra'), ('LG', 'Lagos'), ('ON', 'Ondo'), ('OG', 'Ogun')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='payment',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payapp'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('On the Way', 'On the Way'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='receipt',
            field=models.ImageField(null=True, upload_to='receipt'),
        ),
        migrations.AlterField(
            model_name='payapp',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BW', 'Baby Clothes'), ('SH', 'Shoe'), ('OT', 'Others'), ('BG', 'Bags'), ('CL', 'Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('LC', 'Lacosta'), ('RX', 'Rolex'), ('AD', 'Addidas'), ('GV', 'Givenchy'), ('DG', 'Dolce and Gabanna'), ('SP', 'Supreme'), ('FL', 'Fila'), ('HR', 'Hermes'), ('VS', 'Versace'), ('CK', 'Calvin Klein'), ('GC', 'Gucci'), ('LV', 'Louis Vuitton')], max_length=2),
        ),
    ]
