# Generated by Django 3.2.21 on 2023-09-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230919_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('ON', 'Ondo'), ('AN', 'Anambra'), ('OG', 'Ogun'), ('LG', 'Lagos'), ('NG', 'Niger')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Pending', 'Pending'), ('Delivered', 'Delivered'), ('On the Way', 'On the Way'), ('Packed', 'Packed')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CL', 'Clothes'), ('BG', 'Bags'), ('OT', 'Others'), ('SH', 'Shoe'), ('BW', 'Baby Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('LC', 'Lacosta'), ('RX', 'Rolex'), ('HR', 'Hermes'), ('CK', 'Calvin Klein'), ('GC', 'Gucci'), ('FL', 'Fila'), ('DG', 'Dolce and Gabanna'), ('GV', 'Givenchy'), ('SP', 'Supreme'), ('LV', 'Louis Vuitton'), ('AD', 'Addidas'), ('VS', 'Versace')], max_length=2),
        ),
    ]
