# Generated by Django 3.2.21 on 2023-09-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230919_0434'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_to_cart',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('DL', 'Delta'), ('AN', 'Anambra'), ('ON', 'Ondo'), ('OG', 'Ogun'), ('LG', 'Lagos'), ('NG', 'Niger')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='incart',
            name='product',
        ),
        migrations.AddField(
            model_name='incart',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Canceled', 'Canceled'), ('Delivered', 'Delivered'), ('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On the Way', 'On the Way'), ('Packed', 'Packed')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BG', 'Bags'), ('OT', 'Others'), ('SH', 'Shoe'), ('BW', 'Baby Clothes'), ('CL', 'Clothes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(choices=[('FL', 'Fila'), ('RX', 'Rolex'), ('GC', 'Gucci'), ('LC', 'Lacosta'), ('CK', 'Calvin Klein'), ('HR', 'Hermes'), ('DG', 'Dolce and Gabanna'), ('SP', 'Supreme'), ('GV', 'Givenchy'), ('AD', 'Addidas'), ('VS', 'Versace'), ('LV', 'Louis Vuitton')], max_length=2),
        ),
    ]
